spring:

  redis:

    host: 127.0.0.1

    port: 6379

    timeout: 10s
    lettuce:
      pool:

        min-idle: 0

        max-idle: 8

        max-active: 8

        max-wait: -1m
    password: 123456
  jackson:

    date-format: yyyy-MM-dd HH:mm:ss
    serialization:

      indent_output: true

      fail_on_empty_beans: false

    defaultPropertyInclusion: NON_EMPTY
    deserialization:

      fail_on_unknown_properties: false
    parser:

      allow_unquoted_control_chars: true

      allow_single_quotes: true

