# 图片服务器 minio配置
minio:
  ip: 47.113.108.134:9000
  # minio登录账号密码
  accessKey: minioadmin
  secretKey: minioadmin

  ## 桶名（文件夹）命名规则要符合 亚马逊S3标准 详情可看http://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html
  bucketName:
    ## 照片文件夹
    facility: test